### ISSUE TITLE
cat too adorable for human viewing

### ISSUE THREAD

**Issue by cdaringe** [snopeks/riverthecat#3]
perhaps attempt to blur, to save our eyes from tears of joy

``` css
img.blur {
    -webkit-filter: blur(3px);
    filter: blur(3px);
}
```

:smile_cat:
